collections:
  projects:
    output: true

permalink: /:title
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      parent: "/projects"
      nav:
        sticky: true
      styles:
        - "/assets/css/project.css"
      headItems:
        - "<link rel=\"preload\" as=\"image\" href=\"/assets/img/project-background.svg\">"
  - scope:
      path: ""
    values:
      layout: "master"
